### ISSUE TITLE
可以新增一个 企业微信应用 的运行结果通知方式吗

### ISSUE THREAD

**Issue by xtoys** [x1ah/tieba#1]
[**sample**](https://github.com/whyour/qinglong/blob/develop/sample/notify.py)

**Comment by x1ah** [comment]
可以，简单。明天加一个。

**Comment by x1ah** [comment]
已经加上，试一下可以用吗。@xtoys

**Comment by xtoys** [comment]
> 已经加上，试一下可以用吗。@xtoys

辛苦了 不过想要的是 企业微信应用 那个接口 不是企业微信机器人😂
